### PR TITLE
Update code to use BOSL2.0.669

### PR DESCRIPTION
**Pull request by arnoesterhuizen**
I've updated the code to resolve
- #29 
- `rounding_mask_z` replaced with `rounding_edge_mask` as per the latest version of BOSL2

I did this as a learning exercise of SCAD, so please let me know if I borked up?

### CODE REVIEW

**Comment by charmaur** [comment]
Glad to see someone interested in making improvements!

I am, however, seeing a few issues while using the new BOSL2 version that will need further investigation.

Can you confirm if you're getting the same results?
1. d4i has geometry issues.
2. d4c is missing a '2'.
3. d4, d8, d10, d00, d12, d12r, and d20 all have text rotation issues.

image

**Comment by arnoesterhuizen** [comment]
Ah, now that you point it out, I see what you mean. Let me have a look and see if I can tweak it some more, then update the pull request.

And thanks for this awesome generator; it is really helping me to dive into OpenSCAD!

**Comment by arnoesterhuizen** [comment]
I now see why the upgrade to the latest BOSL2 hasn't happened yet; this is a beast of an update. I'm going to have to chip away at this bit by bit, learning as I go.

**Comment by charmaur** [comment]
I haven't really worked on it in a few years. I do recall past updates messing up text rotation though. Let me know if you get stuck on something and I'll try to help.

**Comment by arnoesterhuizen** [comment]
Creating new pull request after a number of additional changes.

**Pull request closed without merging**
